# Generated by Django 5.1.1 on 2025-01-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='points',
            new_name='money',
        ),
    ]
